### PR TITLE
Update GlyphsFileFormat.md

### LINKED ISSUE #15: Typo in file format description (?)
The [Glyphs File Format document](https://github.com/schriftgestalt/GlyphsSDK/blob/master/GlyphsFileFormat.md) lists `glyphs` ⇒ `layers` ⇒ `path`, but in my `.glyphs` files, it appears to be `paths` not `path`. Is that a typo or are both `paths` and `path` possible?

### PR DESCRIPTION
**Pull request by delucis**
Fixes #15

### CODE REVIEW

**Comment by schriftgestalt** [comment]
I was to quick with a fix myself ;(

**Comment by delucis** [comment]
It’s a good problem to have! Working on some Javascript tools for working with `.glyphs` files, so I wanted to make sure I had a thorough grasp of the spec.

**Comment by schriftgestalt** [comment]
Can you share what you want to do with it?
And do you know https://github.com/googlei18n/glyphsLib

**Comment by delucis** [comment]
Just published what I have so far here: https://github.com/delucis/make-glyphs

I’m working on a music font, and because of the state of music notation software, I needed to export to multiple fonts for compatibility. Maintaining multiple `.glyphs` files means I lose the ability to have a single component as the source for multiple characters and maintaining a single file is not possible because in one export, for example, `J` should be an eighth-note flag, and in another `J` should be a triplet 3.

My own plan is to use the [SMuFL specification](smufl.org) (I also made [SMuFL support files for Glyphs](https://github.com/delucis/smufl-glyphs-info)) for my source file and be able to map these PUA glyphs to various subsets for legacy support. My idea is for a kind of build tool that takes `.glyphs` files as input, and outputs one or more `.glyphs` files, doing things like mapping characters, merging files, etc.

I’m guessing this might have been easier in Python given the existing SDK etc., but I don’t know Python and do know Javascript, so I thought I’d just stick with what I know.

**Pull request merged**
